mandatory parameters

diff --git a/kubectl-deploy/bin/kubectl-deploy b/kubectl-deploy/bin/kubectl-deploy
--- a/kubectl-deploy/bin/kubectl-deploy
+++ b/kubectl-deploy/bin/kubectl-deploy
@@ -15,11 +15,11 @@ set -o errexit
 set -o pipefail
 
 DEFAULT_NAMESPACE="default"
-DEFAULT_TAG="latest"
 DEFAULT_TIMEOUT=120
-API_SERVER="127.0.0.1:8443"
-CERT="ca.crt"
-DOCKER_REPO="docker.io/phantasm"
+API_SERVER=""
+CERT=""
+DOCKER_REPO=""
+DEFAULT_TAG=""
 TOKEN=""
 
 
@@ -66,12 +66,12 @@ display_usage_and_exit() {
   echo "service REQUIRED: The name of the service the script should trigger the Blue/Green deployment" >&2
   echo "image REQUIRED: Name of Docker image" >&2
   echo "-n OPTIONAL: the namespace scope for this CLI request, default is the 'default' namespace" >&2
-  echo "-l OPTIONAL: The new docker tag to deployment, defaults is the 'latest' tag" >&2
+  echo "-l REQUIRED: The new docker tag to deployment" >&2
   echo "-t OPTIONAL: How long to wait for the deployment to be available, defaults to ${DEFAULT_TIMEOUT} seconds, must be greater than 60" >&2
-  echo "-d OPTIONAL: Name of Docker repository, default is \"${DOCKER_REPO}\"" >&2
-  echo "-s OPTIONAL: The address and port of the Kubernetes API server" >&2
-  echo "-c OPTIONAL: Path to a cert file for the certificate authority" >&2
-  echo "-T OPTIONAL: Token for authentication to the K8S API server" >&2
+  echo "-d REQUIRED: Name of Docker repository" >&2
+  echo "-s REQUIRED: The address and port of the Kubernetes API server" >&2
+  echo "-c REQUIRED: Path to a cert file for the certificate authority" >&2
+  echo "-T REQUIRED: Token for authentication to the K8S API server" >&2
   exit 1
 }
 
@@ -96,6 +96,10 @@ do
         *) display_usage_and_exit
     esac
 done
+
+if [[ -z ${docker_repo} || -z ${cert} || -z ${token} || -z ${server} || -z ${tag} ]]; then
+  display_usage_and_exit
+fi
 
 shift $((OPTIND-1))
 if [ "$#" -ne 2 ] ; then   
